channels:
 - conda-forge
 - bioconda
dependencies:
 - conda-forge::r-seurat=4.0.0
 - conda-forge::r-rlang=0.4.9
 - bioconda::r-signac=1.1.1
 - conda-forge::r-cairo=1.5_12.2
 - conda-forge::r-devtools=2.3.2
 - bioconda::bioconductor-limma=3.46.0
 - conda-forge::font-ttf-ubuntu=0.83
 - conda-forge::r-hdf5r=1.3.3
